[
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Too few mandhyps! term 1","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0","Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Too many mand hyps! step 3","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,0,"Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Freeness constraint mismatch: calculated [\"1,0\"]; declared []","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,"Deps.0"]}},
    {"Core":[[0],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Hyp unify fail: step Deps.0","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,"Deps.0"]}},
    {"Core":[[[1,1,0]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Hyp unify fail: step Deps.0","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,"Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Stack underflow: step Deps.0","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":[1,"Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Final stack length 2","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0","Hyps.0",1,"Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Leftover mand hyp on stack","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,"Deps.0",1]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,0]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Stack doesn't match concl","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":["Hyps.0",1,"Deps.0"]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Final stack length 0","HypNames":["hyp"],"DepNames":["19.21ai"],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],[0,1]]],"Proof":[["hyp",1,"Deps.0"]]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Final stack length 0","HypNames":["hyp"],"DepNames":[],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[],"Proof":[[0,0,2]]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Final stack length 0","HypNames":["hyp"],"DepNames":[],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[],"Proof":[[[],0,2]]}},
    {"Core":[[[0,0,2]],[0,0,[1,1,2]],[[0,1]]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Final stack length 0","HypNames":["hyp"],"DepNames":[],"VarNames":["ph","x","ps"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[],"Proof":[]}},
    {"Core":[[],[0,[1,0,[1,0,1]],[1,0,[1,0,1]]],[]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Binding variables not distinct: 0 at step 3","HypNames":[],"DepNames":["ax-7"],"VarNames":["x","ph"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[],[0,[1,0,[1,1,2]],[1,1,[1,0,2]]],[]],[0,1]]],"Proof":[0,0,1,"Deps.0"]}},
    {"Core":[[],[0,0,0],[]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Thm Mismatch: Final stack has [0,0,[1,1,0]] but wanted [0,0,0]","HypNames":[],"DepNames":["alnfi"],"VarNames":["ph","A"],"TermNames":["->","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[],[0,0,[1,1,0]],[[0,1]]],[0,1]]],"Proof":[0,1,"Deps.0"]}},
    {"Core":[[],[0,0,0],[]],"FreeMaps":{"2":{"0":[]}},"Skin":{"Name":"Expected binding var for 1; got [1,1,2]","HypNames":[],"DepNames":["alnfi"],"VarNames":["ph","x","y"],"TermNames":["->","+","A."],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[],[0,0,[1,1,0]],[[0,1]]],[0,2]]],"Proof":[0,[1,1,2],"Deps.0"]}},
    {"Core":[[],[0,0,[0,1,0]],[]],"FreeMaps":{},"Skin":{"Name":"Unknown string step AntecedentIntroduction at 2","HypNames":[],"DepNames":[],"VarNames":["p","q"],"TermNames":["foo.->"],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[],"Proof":[0,1,"AntecedentIntroduction"]}},
    {"Core":[[],[0,[1,0,[2,0,[3]]],[2,0,[3]]],[]],"FreeMaps":{"1":{"0":[]}},"Skin":{"Name":"Freeness violation! 0 free in [2,0,[3]] at step Deps.0@2","HypNames":[],"DepNames":["ThereExistsAddRemove"],"VarNames":["z"],"TermNames":["<->","E.","=","1"],"Delimiters":[]},"Tree":{"Cmd":"thm","Deps":[[[[],[0,[1,0,1],1],[[1,0]]],[0,1]]],"Proof":[0,[2,0,[3]],"Deps.0"]}}

]